# Generated by Django 3.0.2 on 2020-09-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clg_name',
        ),
    ]
