# Generated by Django 3.0.2 on 2020-09-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_clg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clg_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
